-- MySQL Script generated by MySQL Workbench
-- Fri Jul  6 17:39:49 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Grupos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Grupos` (
  `idGrupos` INT UNSIGNED NOT NULL,
  `NombreGrupo` VARCHAR(45) NULL,
  `MatriculaAlumnos` INT UNSIGNED NOT NULL,
  `IdMaestro` INT UNSIGNED NOT NULL,
  `Horas a realizar` INT NULL,
  `Actividad` VARCHAR(45) NULL,
  PRIMARY KEY (`idGrupos`, `MatriculaAlumnos`, `IdMaestro`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Alumnos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Alumnos` (
  `Matricula` INT UNSIGNED NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  `Carrera` VARCHAR(45) NULL,
  `Nivel` INT NULL,
  `Horas realizadas` INT NULL,
  `UltimoIngresoFecha` DATETIME NULL,
  `UltimoIngresoHorario` INT NULL,
  PRIMARY KEY (`Matricula`),
  CONSTRAINT `Matricula`
    FOREIGN KEY (`Matricula`)
    REFERENCES `mydb`.`Grupos` (`MatriculaAlumnos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Maestros`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Maestros` (
  `IdMaestros` INT UNSIGNED NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  `Turno` VARCHAR(45) NULL,
  PRIMARY KEY (`IdMaestros`),
  CONSTRAINT `IdMaestros`
    FOREIGN KEY (`IdMaestros`)
    REFERENCES `mydb`.`Grupos` (`IdMaestro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Usuarios` (
  `IdUsuario` INT NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  `Tipo` VARCHAR(45) NULL,
  PRIMARY KEY (`IdUsuario`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
